# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [11]:
# Matthew Lett
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

from pprint import pprint

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [12]:
cities = pd.read_csv('../WeatherPy/Output/City_Output.csv')
cities.dropna(inplace=True, how='any')
cities.head()

,City,Latitude,Longitude,Max Temperature,Humidity,Cloud Coverage,Windspeed,Country,City Date Time,Weather Description
0,okato,-39.2000,173.8833,51.69,86.0,86.0,4.61,NZ,2021-07-24 04:51:50,few clouds
1,eureka,40.8021,-124.1637,56.35,78.0,78.0,1.01,US,2021-07-24 04:50:02,clear sky
2,ushuaia,-54.8000,-68.3000,37.06,75.0,75.0,5.75,AR,2021-07-24 04:50:39,light rain
3,mataura,-46.1927,168.8643,44.56,87.0,87.0,3.38,NZ,2021-07-24 04:53:03,scattered clouds
4,xinqing,48.2333,129.5000,92.30,33.0,33.0,12.33,CN,2021-07-24 04:53:04,few clouds

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [13]:
# Access maps with unique API key
gmaps.configure(api_key=g_key)

figure_layout = {
    'width': '275px',
    'height': '275px',
    'border': '1px solid black',
    'padding': '1px',
    'zoom_level': 12
}
# gmaps.figure(layout=figure_layout)

# locations
locations = cities[['Latitude', 'Longitude']]

# heat weight
humidities = cities['Humidity']

# create the map
fig = gmaps.figure(layout=figure_layout)

# create the heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidities,
                                dissipating=False, max_intensity=10,
                                point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='275px', padding='1px', width='275px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [14]:
ideal_cities = cities.loc[(cities['Max Temperature'] < 80) & (cities['Max Temperature'] > 70) & (cities['Humidity'] <50)]
ideal_cities

,City,Latitude,Longitude,Max Temperature,Humidity,Cloud Coverage,Windspeed,Country,City Date Time,Weather Description
10,batagay-alyta,67.8006,130.4114,74.75,37.0,37.0,7.90,RU,2021-07-24 04:53:06,few clouds
15,awjilah,29.1081,21.2869,76.89,47.0,47.0,9.10,LY,2021-07-24 04:53:07,clear sky
20,airai,-8.9266,125.4092,77.67,22.0,22.0,5.48,TL,2021-07-24 04:53:09,broken clouds
121,sao geraldo do araguaia,-6.4006,-48.5550,72.23,47.0,47.0,3.40,BR,2021-07-24 04:53:42,clear sky
138,cedar city,37.6775,-113.0619,71.40,44.0,44.0,1.32,US,2021-07-24 04:53:48,overcast clouds
152,udachnyy,66.4167,112.4000,71.62,44.0,44.0,12.82,RU,2021-07-24 04:53:53,broken clouds
161,zhigansk,66.7697,123.3711,74.08,36.0,36.0,12.35,RU,2021-07-24 04:53:56,overcast clouds
190,hayden,47.7660,-116.7866,74.39,43.0,43.0,5.75,US,2021-07-24 04:54:07,clear sky
302,ruteng,-8.6136,120.4721,76.64,41.0,41.0,2.53,ID,2021-07-24 04:54:45,scattered clouds
329,gizeh,30.0081,31.2109,79.54,39.0,39.0,9.37,EG,2021-07-24 04:54:54,clear sky
356,rawlins,41.7911,-107.2387,75.09,26.0,26.0,10.36,US,2021-07-24 04:52:32,clear sky
402,aksarayskiy,46.7924,48.0119,76.98,41.0,41.0,10.18,RU,2021-07-24 04:55:20,clear sky
405,krasnyy chikoy,50.3643,108.7512,73.31,46.0,46.0,6.31,RU,2021-07-24 04:55:21,few clouds
414,mikhaylovka,50.0600,43.2379,72.27,45.0,45.0,6.73,RU,2021-07-24 04:55:26,clear sky
489,nikolayevskaya,47.6139,41.5023,74.55,42.0,42.0,7.18,RU,2021-07-24 04:55:52,clear sky
507,awbari,26.5921,12.7805,75.04,32.0,32.0,8.93,LY,2021-07-24 04:55:58,clear sky
509,ulaangom,49.9811,92.0667,79.20,46.0,46.0,9.86,MN,2021-07-24 04:55:59,scattered clouds
519,mama,58.3106,112.8986,77.67,45.0,45.0,8.10,RU,2021-07-24 04:56:02,scattered clouds
559,kysyl-syr,63.8986,122.7617,76.17,44.0,44.0,4.07,RU,2021-07-24 04:56:15,overcast clouds
603,batagay,67.6333,134.6333,79.75,28.0,28.0,4.23,RU,2021-07-24 04:56:30,broken clouds
604,green river,41.5286,-109.4662,74.19,30.0,30.0,1.01,US,2021-07-24 04:56:30,overcast clouds
619,toora-khem,52.4675,96.1100,76.64,41.0,41.0,1.77,RU,2021-07-24 04:56:35,overcast clouds

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [15]:
hotel_df = ideal_cities[['City', 'Country', 'Latitude', 'Longitude']]
hotel_df['Hotel Name'] = ''
hotel_df.reset_index(drop=True)

C:\Users\matt\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                       City Country  Latitude  Longitude Hotel Name
0             batagay-alyta      RU   67.8006   130.4114
1                   awjilah      LY   29.1081    21.2869
2                     airai      TL   -8.9266   125.4092
3   sao geraldo do araguaia      BR   -6.4006   -48.5550
4                cedar city      US   37.6775  -113.0619
5                  udachnyy      RU   66.4167   112.4000
6                  zhigansk      RU   66.7697   123.3711
7                    hayden      US   47.7660  -116.7866
8                    ruteng      ID   -8.6136   120.4721
9                     gizeh      EG   30.0081    31.2109
10                  rawlins      US   41.7911  -107.2387
11              aksarayskiy      RU   46.7924    48.0119
12           krasnyy chikoy      RU   50.3643   108.7512
13              mikhaylovka      RU   50.0600    43.2379
14           nikolayevskaya      RU   47.6139    41.5023
15                   awbari      LY   26.5921    12.7805
16                 ulaangom      MN   49.9811    92.0667
17                     mama      RU   58.3106   112.8986
18                kysyl-syr      RU   63.8986   122.7617
19                  batagay      RU   67.6333   134.6333
20              green river      US   41.5286  -109.4662
21               toora-khem      RU   52.4675    96.1100

In [20]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# set up a parameters dictionary
params = {
    "location": f'37.6775, -113.0619',
    "radius": 5000,
    "keyword": 'hotel',
#     "rankby": "distance",
    "key": g_key
}

response = requests.get(base_url, params=params).json()
    
# extract results
results = response['results']

In [22]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# set up a parameters dictionary
params = {
    "radius": 5000,
    "keyword": 'lodging',
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get city location from df
    lat = row['Latitude']
    lng = row['Longitude']
    city = row['City']

    # add keyword to params dict
    params['location'] = f'{lat},{lng}'
       

    # assemble url and make API request
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
   
    try:
        
        print(f'Getting result for {city}')
        # add the results to the dataframe
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

# check the results
hotel_df.head()

Getting result for batagay-alyta
Missing field/result... skipping.
Getting result for awjilah
Missing field/result... skipping.
Getting result for airai
Missing field/result... skipping.
Getting result for sao geraldo do araguaia
Getting result for cedar city
Getting result for udachnyy
Getting result for zhigansk
Getting result for hayden
Getting result for ruteng
Getting result for gizeh
Getting result for rawlins
Getting result for aksarayskiy
Missing field/result... skipping.
Getting result for krasnyy chikoy
Getting result for mikhaylovka
Getting result for nikolayevskaya
Missing field/result... skipping.
Getting result for awbari
Getting result for ulaangom
Missing field/result... skipping.
Getting result for mama
Missing field/result... skipping.
Getting result for kysyl-syr
Missing field/result... skipping.
Getting result for batagay
Getting result for green river
Getting result for toora-khem
Missing field/result... skipping.

                        City Country  Latitude  Longitude          Hotel Name
10             batagay-alyta      RU   67.8006   130.4114
15                   awjilah      LY   29.1081    21.2869
20                     airai      TL   -8.9266   125.4092
121  sao geraldo do araguaia      BR   -6.4006   -48.5550    Hotel Andorinhas
138               cedar city      US   37.6775  -113.0619  Abbey Inn & Suites

In [18]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [19]:
# Add marker layer ontop of heat map
figure_layout = {
    'width': '275px',
    'height': '275px',
    'border': '1px solid black',
    'padding': '1px',
    'zoom_level': 12
}
fig = gmaps.figure(layout=figure_layout)
# gmap marker layer on top of a heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='275px', padding='1px', width='275px'))